"""
Generates Power BI Row-Level Security (RLS) TMDL from Tableau workbook analysis.

Tableau security patterns detected:
  - USERNAME()    → USERPRINCIPALNAME()
  - USERDOMAIN()  → USERDOMAIN() (kept, same semantic)
  - ISMEMBEROF()  → flagged as manual (no direct DAX equivalent)
  - Calculated field used as a row-level permission gate
"""
from __future__ import annotations
import re
from pathlib import Path
from typing import List
from uuid import uuid4

from accelerator.ir.schema import IRMigrationUnit, TranslationResult
from accelerator.generators.tmdl_generator import _safe_table_name

_USERNAME_RE   = re.compile(r'\bUSERNAME\s*\(\s*\)',    re.IGNORECASE)
_USERDOMAIN_RE = re.compile(r'\bUSERDOMAIN\s*\(\s*\)',  re.IGNORECASE)
_ISMEMBEROF_RE = re.compile(r'\bISMEMBEROF\s*\(',       re.IGNORECASE)


def _find_security_fields(unit: IRMigrationUnit) -> list[dict]:
    found = []
    for ds in unit.data_sources:
        for col in ds.columns:
            if not col.formula:
                continue
            has_user   = bool(_USERNAME_RE.search(col.formula))
            has_domain = bool(_USERDOMAIN_RE.search(col.formula))
            has_member = bool(_ISMEMBEROF_RE.search(col.formula))
            if has_user or has_domain or has_member:
                table = _safe_table_name(ds.tables[0].name if ds.tables else ds.name)
                found.append({
                    "datasource":      ds.name,
                    "table":           table,
                    "column":          col.name,
                    "formula":         col.formula,
                    "has_username":    has_user,
                    "has_userdomain":  has_domain,
                    "has_ismemberof":  has_member,
                })
    return found


def _dax_filter(field: dict) -> tuple[str, bool]:
    """Return (dax_expression, is_manual_required)."""
    col   = field["column"]
    formula = field["formula"]

    if field["has_ismemberof"]:
        # No direct DAX equivalent — must be handled with Azure AD groups or custom security tables
        return (
            f"// ISMEMBEROF has no DAX equivalent\n"
            f"// Tableau: {formula}\n"
            f"// Option A: Use an external security table joined on [UserEmail] = USERPRINCIPALNAME()\n"
            f"// Option B: Use Power BI workspace-level RLS with Azure AD groups\n"
            f"true()",
            True,
        )

    if field["has_username"]:
        dax = _USERNAME_RE.sub("USERPRINCIPALNAME()", formula)
        dax = _USERDOMAIN_RE.sub("USERDOMAIN()", dax)
        # Try to produce a clean table-filter expression: [col] = USERPRINCIPALNAME()
        simple = re.sub(r'\[' + re.escape(col) + r'\]\s*==?\s*USERPRINCIPALNAME\(\)',
                        '', dax).strip(" &|")
        if not simple:
            return f"[{col}] = USERPRINCIPALNAME()", False
        return f"[{col}] = USERPRINCIPALNAME()", False

    if field["has_userdomain"]:
        return f"[{col}] = USERDOMAIN()", False

    return f"[{col}] = USERPRINCIPALNAME()", False


def _role_tmdl(role_name: str, table_name: str, filter_expr: str,
               is_manual: bool) -> str:
    lines = [
        f"role '{role_name}'",
        f"    annotation PBI_Id = \"{uuid4()}\"",
        "",
        f"    tablePermission '{table_name}'",
    ]
    if is_manual:
        for ln in filter_expr.splitlines():
            lines.append(f"        {ln}")
    else:
        lines.append(f"        filterExpression: \"{filter_expr}\"")
    lines.append("")
    return "\n".join(lines)


def _template_role_tmdl(table_name: str) -> str:
    return "\n".join([
        "// No Tableau username/group security detected in this workbook.",
        "// Template role is provided — add DAX table filter expressions as required.",
        "",
        "role 'Row Level Security'",
        f"    annotation PBI_Id = \"{uuid4()}\"",
        "",
        f"    tablePermission '{table_name}'",
        "        // TODO: replace with your DAX filter, e.g.:",
        "        //   [UserEmail] = USERPRINCIPALNAME()",
        "        filterExpression: \"true()\"",
        "",
    ])


def generate_security_tmdl(unit: IRMigrationUnit) -> str:
    header = "\n".join([
        "// ============================================================",
        "// Power BI Row-Level Security (RLS)",
        "// Generated by Tableau → Power BI Accelerator",
        "// IMPORTANT: Test every role with 'Modeling → View as roles'",
        "//            in Power BI Desktop before publishing.",
        "// ============================================================",
        "",
    ])

    security_fields = _find_security_fields(unit)

    if not security_fields:
        first_table = _safe_table_name(
            unit.data_sources[0].tables[0].name
            if unit.data_sources and unit.data_sources[0].tables
            else unit.data_sources[0].name if unit.data_sources else "Table"
        )
        return header + _template_role_tmdl(first_table)

    # Group fields by table
    by_table: dict[str, list] = {}
    for f in security_fields:
        by_table.setdefault(f["table"], []).append(f)

    parts = [header]
    for table_name, fields in by_table.items():
        role_name = f"{table_name} Security"
        dax_parts: list[str] = []
        has_manual = False
        manual_comments: list[str] = []

        for f in fields:
            expr, is_manual = _dax_filter(f)
            if is_manual:
                has_manual = True
                manual_comments.append(expr)
            else:
                dax_parts.append(expr)

        if dax_parts:
            combined = " && ".join(dax_parts)
            parts.append(_role_tmdl(role_name, table_name, combined, False))
        else:
            # All manual — emit template with comments
            combined = "\n".join(manual_comments) if manual_comments else "true()"
            parts.append(_role_tmdl(role_name, table_name, combined, True))

    return "\n".join(parts)


def generate_security(unit: IRMigrationUnit, output_dir: Path) -> List[TranslationResult]:
    """Write roles/*.tmdl into the SemanticModel folder."""
    results: List[TranslationResult] = []

    # Support both pre-package (SemanticModel/) and post-package ({name}.SemanticModel/)
    model_dir = output_dir / "SemanticModel"
    if not model_dir.exists():
        candidates = list(output_dir.glob("*.SemanticModel"))
        model_dir = candidates[0] if candidates else output_dir / "SemanticModel"
    model_dir.mkdir(parents=True, exist_ok=True)

    roles_dir = model_dir / "roles"
    roles_dir.mkdir(exist_ok=True)

    security_fields = _find_security_fields(unit)
    has_real = bool(security_fields)

    tmdl = generate_security_tmdl(unit)

    role_name = "Row Level Security" if not has_real else "Security"
    role_file = roles_dir / f"{_safe_table_name(role_name)}.tmdl"
    role_file.write_text(tmdl, encoding="utf-8")

    caveats = [
        "Review all RLS roles in Power BI Desktop before publishing.",
        "Test with 'Modeling → View as roles' to verify filter behavior.",
    ]
    if any(f["has_ismemberof"] for f in security_fields):
        caveats.append(
            "ISMEMBEROF() has no DAX equivalent — requires Azure AD group table or workspace RLS."
        )

    results.append(TranslationResult(
        source_id=unit.id,
        target_artifact=tmdl,
        target_kind="model",
        confidence=0.80 if has_real else 0.50,
        method="deterministic",
        caveats=caveats,
        needs_review=True,
        review_priority="high" if has_real else "medium",
        rationale=(
            "RLS migrated from Tableau USERNAME()/USERDOMAIN() security fields."
            if has_real
            else "No Tableau security detected — template RLS role generated for review."
        ),
    ))
    return results
